* New todo list for hp15c alone, 2018-06-24
[ ] adjust the lcd panel placement of digits
[ ] adjust the lcd panel placement of indicators
[ ] adjust the lcd indicator font
[ ] figure out how to adjust fonts as the calculator resizes
[ ] get rid of the 600px limit and figure out what to do instead.
[ ] figure out how to keep the menubutton with the about page.
[ ] figure out the adaptive break for portrait mode on phones
	keep the core 4x5 keypad
	but the [f] and [g] and [<-] and [on] are sort of
	essential to the works, and the other keys get used,too.
	The android calc is pretty neat, but swiping breaks the
	key concentration, pretty as it is.  Shifting sucks for
	accessability, you have to tab to the shift key, then tab
	to the operation, I should check with a user to see what
	they think.
	Which is pertinent because I'm thinking shift keys all the
	way for paging through the overlays.  Bottom row in the
	narrow layout is:
	[on] [f] [g] [o] [<-]
	where [on] is needed to clear errors, [f] and [g] for
	access to alternate key functions, [o] cycles through
	the overlays, [g][o] cycles in reverse.
[ ] reorganize the key information so that
	each key has a unique identifier which can be searched in
	code without consulting unicode.org,
	that identifier translates naturally into the actual key
	cap label by some mindless transformation,
	the key definitions are stored under the identifier,
	the key layouts are simply arrays of identifiers.
[ ] the adaptive layout with overlay shifts produces multiple
	layouts containing the same keys in the same and/or
	different locations.

	
